export const PROJECT_TITLE = "Project 1A: Front End Developer Multi Step Loan Application Form";

export const LOAN_TYPES = {
  personal: {
    label: "Personal Loan",
    max: 1000000,
    minTenure: 12,
    maxTenure: 60,
    rate: 10.5,
    purposes: ["Debt consolidation", "Medical expense", "Education", "Travel", "Wedding", "Other"],
  },
  home: {
    label: "Home Loan",
    max: 10000000,
    minTenure: 60,
    maxTenure: 360,
    rate: 8.5,
    purposes: ["New home purchase", "Home construction", "Home renovation", "Balance transfer"],
  },
  business: {
    label: "Business Loan",
    max: 5000000,
    minTenure: 12,
    maxTenure: 120,
    rate: 14,
    purposes: ["Working capital", "Equipment purchase", "Inventory", "Business expansion"],
  },
};

export const MIN_LOAN_AMOUNT = 50000;
export const DRAFT_KEY = "project1a.loanApplication.draft";
export const DRAFT_VERSION = 1;
export const DRAFT_TTL_MS = 72 * 60 * 60 * 1000;

export const DEFAULT_VALUES = {
  loanType: "personal",
  loanAmount: "",
  tenure: "",
  purpose: "",
  referralCode: "",
  fullName: "",
  dob: "",
  gender: "",
  maritalStatus: "",
  fatherName: "",
  motherName: "",
  email: "",
  mobile: "",
  alternateMobile: "",
  pan: "",
  panVerified: false,
  aadhaar: "",
  aadhaarVerified: false,
  aadhaarConsent: false,
  voterId: "",
  passport: "",
  currentAddress1: "",
  currentAddress2: "",
  currentPin: "",
  currentCity: "",
  currentState: "",
  currentPostOffice: "",
  pinDerivedState: "",
  residenceType: "",
  yearsAtAddress: "",
  monthlyRent: "",
  previousAddress: "",
  samePermanent: true,
  permanentAddress1: "",
  permanentPin: "",
  permanentCity: "",
  permanentState: "",
  employmentType: "salaried",
  companyName: "",
  designation: "",
  monthlySalary: "",
  salariedExperience: "",
  businessName: "",
  businessType: "",
  annualTurnover: "",
  yearsInBusiness: "",
  selfMonthlyIncome: "",
  businessAddress: "",
  gstNumber: "",
  coName: "",
  coRelationship: "",
  coPan: "",
  coPanVerified: false,
  coIncome: "",
  coConsent: false,
  coSignature: "",
  documents: {},
  signature: "",
  consentAccuracy: false,
  consentCredit: false,
  consentTerms: false,
  consentCommunication: false,
};
